Reorganize docker images to use the same tag
Teradata/presto pull request #354
Opened 2016-09-21 20:40 UTC by sanjay990

2016-09-21 20:40 UTC, sanjay990 commented
@ebd2 @ArturGajowy

2016-09-21 21:23 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
please keep the parametrization in place. So it'd be sth like
```
export DOCKER_IMAGE_VERSION=7a742e2
export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-"teradatalabs/cdh5-hive:$DOCKER_IMAGE_VERSION"}
```

2016-09-21 21:24 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
also rename the variable to `DOCKER_IMAGES_VERSION` (plural)

2016-09-21 21:37 UTC, sanjay990 commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
@ArturGajowy : What's the advantage of defining the variable
export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-"teradatalabs/cdh5-hive:$DOCKER_IMAGE_VERSION"}
We don't have that for kerberos images

2016-09-21 21:37 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
after giving it some thought I think we shouldn't introduce DOCKER_IMAGE_VERSION parametrization to the compose files. I wouldn't like the `compose-commons.sh` to grow to another `run-on-docker.sh` (BTW in Warsaw we jokingly call it 'dockto'...). So, if the only reason for introducing the `DOCKER_IMAGE_VERSION` variable is avoiding duplication, I'd say the cost of more complexity in compose-commons might not be worth it.

OTOH Changing the version used from sequence number ('4') to git hash looks like a good change and will enable for seamless search-and-replace the next time we need to update the image version. After replacing, the change can be further validated by running:
```
$ ./presto-product-tests/conf/docker/singlenode/compose.sh config | grep image
    image: teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f
    image: teradatalabs/cdh5-hive:4
    image: teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f
    image: mysql
    image: postgres
    image: teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f
```

2016-09-21 21:41 UTC, ArturGajowy requested changes
LGTM % comments

2016-09-21 21:45 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
See the comment above :) We don't have the hdp-master-and-slave-in-one image (the dh5-hive equivalent) yet, but once we have it, no changes are needed in presto itself - just setting the env variable in `presto-checks` or wherever we run

2016-09-21 22:15 UTC, ArturGajowy approved these changes

2016-09-21 22:16 UTC, sanjay990 commented on presto-product-tests/conf/docker/common/compose-commons.sh
> -export HADOOP_MASTER_IMAGE=${HADOOP_MASTER_IMAGE:-'teradatalabs/cdh5-hive:4'}
:+1:

2016-09-22 13:55 UTC, ebd2 approved these changes
LGTM

2016-09-22 15:42 UTC, merged