Support https communication between nodes
Teradata/presto pull request #365
Opened 2016-09-30 20:11 UTC by arhimondr

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Disable HTTP endpoint. Leaving HTTP endpoint enabled leads to a security hole.
put this in WARNING

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Generate Java Keystore File
are these sub-sections?

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Enable HTTPS endpoint.
subsection?

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +    http-server.https.port=7778
is this port number configurable?

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Domains must be in the same parent domain to be able to easy generate custom SSL \
Is this in node.properties?

2016-09-30 20:21 UTC, akshatnair commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +
Which file to add this to?

2016-09-30 20:21 UTC, akshatnair commented on presto-main/src/main/java/com/facebook/presto/server/InternalHttpClientConfigurationModule.java
> +            checkState(config.getKeyStorePath() == null);
should be getKeyStorePassword

2016-10-03 13:33 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/server/InternalHttpClientConfigurationModule.java
> +            checkState(config.getKeyStorePath() == null);
Nice catch, thanks

2016-10-03 13:40 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Generate Java Keystore File
I'm going to make them bullet points. All these steps are part of the same guideline.

2016-10-03 13:41 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Enable HTTPS endpoint.
ditto

2016-10-03 13:42 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Domains must be in the same parent domain to be able to easy generate custom SSL \
For the simplicity i suggest above to modify only `config.properties`. We can implement auto-domain assignment in `presto-admin`, and modify `node.properties` there.

2016-10-03 13:42 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +
All the properties must be added to the `config.properies` files, as it is said in section above.

2016-10-03 18:03 UTC, ebd2 requested changes

2016-10-03 18:03 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +2. Specify node's domains. Every node must have it's own domain configured.
Do you mean domain or FQDN here? Domain implies a container for hosts, whereas coordinator.example.com is a host, not a container.

2016-10-03 18:03 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +Domains must be in the same parent domain to be able to easy generate custom SSL
s/easy/easily/

2016-10-03 18:03 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +      [Unknown]:  *.example.com
Is this literally '*', or should the * be replaced by the hostname you're generating a certificate for?

2016-10-03 18:03 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +    Is CN=eiger, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown correct?
CN should match the value from the firstname/lastname question

2016-10-03 18:03 UTC, ebd2 commented on presto-main/src/main/java/com/facebook/presto/server/InternalHttpClientConfigurationModule.java
> +            config.setKeyStorePath(configuration.getKeyStorePath());
Will this fail on startup if the keystore doesn't exist/isn't readable? Fail fast would be highly desirable.

2016-10-03 19:09 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +      [Unknown]:  *.example.com
It is literally. Every presto node must be able to connect to any other node within the same cluster. We can create private certificates for every single node for the exact domain, and than specify it for server, and create a keystore that has all the public keys for all the domains, and specify it for client. But for the simplicity we suggest to just create one single keystore for the base domain with `*`, and distribute it across the cluster.

2016-10-03 19:32 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +      [Unknown]:  *.example.com
I think you should discuss those two options between "3. Generate..." and the code block. What you've written already should work if you change the we's to you's.

2016-10-03 19:47 UTC, arhimondr commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +      [Unknown]:  *.example.com
@ebd2 done

2016-10-03 19:56 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +exact domain, and than specify it for the server (`http-server.https.keystore.path`), and create a
s/than/then/

2016-10-03 19:57 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +exact domain, and than specify it for the server (`http-server.https.keystore.path`), and create a
Actually, this should probably be: It is possible..., specify it for the server..., create keystore..., and specify it....

2016-10-03 19:58 UTC, ebd2 commented on presto-docs/src/main/sphinx/security/internal-communication.rst
> +client (`http-client.https.keystore.path`). But for simplicity single keystore for the base domain
Suggest: "For simplicity, you can create a single keystore for the base domain with a wildcard"

2016-10-03 19:59 UTC, ebd2 commented
LGTM % grammar in the docs. If you think the code is final, I can edit for you if you want.

2016-10-03 20:07 UTC, arhimondr commented
> If you think the code is final

Yes, it is.

> I can edit for you if you want

That would be much appreciated

2016-10-03 21:49 UTC, closed without merging