Add SQL Server connector
Teradata/presto pull request #389
Opened 2016-10-17 19:40 UTC by sanjay990

2016-10-17 19:41 UTC, sanjay990 commented
@akshatnair @petroav

2016-10-19 19:21 UTC, sanjay990 commented
@rschlussel : Plz review

2016-10-19 19:43 UTC, rschlussel-zz requested changes
You'll also need to add the sql-server plugin to the plugins section of presto.xml (in the presto-server module) so that it gets packaged up.

2016-10-19 19:43 UTC, rschlussel commented on presto-sqlserver/src/main/java/com/facebook/presto/plugin/sqlserver/SqlServerClient.java
> +            return (Driver) Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").newInstance();
Do we not have this class at compile time?  Why are we using reflection here when the other JDBC Plugins instantiate their drivers directly?

2016-10-19 21:05 UTC, sanjay990 commented on presto-sqlserver/src/main/java/com/facebook/presto/plugin/sqlserver/SqlServerClient.java
> +            return (Driver) Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").newInstance();
Yes, its possible we don't have this class at compile time. If the user doesn't want SQL Server connector,he won't install SQL Server JDBC jar. For other drivers, we download it from maven central and have by default. For SQL Server, user has to manually download and install the drivers before using this connector.

2016-10-20 06:20 UTC, akshatnair commented
Please add tests like we have for postgres and mysql

2016-10-21 21:45 UTC, sanjay990 commented
@rschlussel - https://github.com/Teradata/presto/pull/389/commits/6dd97afb474b9460ac6e71ee68b46d6328e77b44

2016-10-21 21:48 UTC, sanjay990 commented
@akshatnair - Yes, I am looking into that. We run PostgreSQL and MySQL as embedded database for tests, it's not possible to do the same with SQL Sever. I am looking into running H2 database with `MS SQL Server Compatibility Mode`

2017-01-12 01:32 UTC, sanjay990 commented
New PR for SQL Server - https://github.com/Teradata/presto/pull/481

2017-01-12 01:32 UTC, closed without merging