Refactor in Annotation based functions (WIP)
Teradata/presto pull request #396
Opened 2016-10-24 09:49 UTC by fiedukow

Disclaimer:
**Right now this is mostly for preview purposes, as the work isn't complete yet.**

This refactor is continuation of https://github.com/prestodb/presto/pull/5381#issuecomment-228121580 based on comments collected there.

The main goals here are:
 * Allow all applicable annotation syntax from ParametricScalar to ParametricAggregates
 * Align two versions of parallel annotations engines where possible, extract whatever they have in common
 * Use newly created syntax to simplify existing aggregates implementations, namely MIN/MAX

Currently missing:
[] - Still existing duplicates of code reading annotations
[] - Complex tests set for annotation based functions
[] - Usage of extracted ParametricImplementation abstraction
[] - Support for specialized aggregates implementations
[] - Support for constructor based injections in annotations
[] - Benchmarks to check that there was no drop in MIN/MAX performance
[] - Check if it is possible to simplify more aggregates implementations

It is however visible what's the general direction of those changes so PR is created to discuss the basis with larger audience.

2016-11-04 15:42 UTC, losipiuk requested changes

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                                aggregationAnnotation.approximate() ? FunctionKind.APPROXIMATE_AGGREGATE : FunctionKind.AGGREGATE,
remove FK.A_A

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementations.java
> +    // These are implementations for when a type parameter binds to a specific native container type
for case when

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementations.java
> +        this.exactImplementations = requireNonNull(exactImplementations);
add messages for "requireNonNull" and use Immutable*.copyOf

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/BindableAggregationFunction.java
> +        return details.getDescription().isPresent() ? details.getDescription().get() : "";
```
return details.getDescription().orElse("")
```

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +    public AggregationImplementation(Signature signature, Class<?> definitionClass, Class<?> stateClass, Method inputFunction, Method outputFunction)
`requireNotNull`?

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationHeader.java
> +        this.description = description;
`requireNotNull`?

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/BindableAggregationFunction.java
> +    AggregationHeader details;
is `details` variable name intentional or a consequence of former name of the class which is now called `AggregateHeader`?

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +            if (containsMetaParameter(annotations)) {
it would be nicer to have
`Optional<Annotation> getMetaParameter(annotations)`

and use:

```
getMetataParameter(annotations).ifPresent(annotation -> ...)
```

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                if (annotation instanceof TypeParameter) {
add comment why typeParameters and literalParameters are checked vs lists which are built above.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/metadata/FunctionListBuilder.java
> +    public FunctionListBuilder aggregate(Class<?> aggregationDefinition)
This is reintroduce of method removed in previous commit. Remove this.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/metadata/SqlAggregationFunction.java
> +    public static List<SqlAggregationFunction> createFunctionByAnnotations(Class<?> aggregationDefinition)
`createFunctionByAnnotations` and `createFunctionsByAnnotations` is the same. Remove one.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +            for (Method outputFunction : getOutputFunctions(aggregationDefinition, stateClass)) {
getOutputFunctions(def, state) and getInputFunctions(def, state) should be called getOutputFunction and getInputFunction and return Optional<...>.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +        int stateId = findAggregationStateParamId(inputFunction);
stateParamId?

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/annotations/ImplementationDependency.java
> +    public static class Factory
why having static Factory class with just static factory method. Move factory method directly to ImplementationDependency

2016-11-04 15:42 UTC, losipiuk commented on presto-spi/src/main/java/com/facebook/presto/spi/function/DependencyAnnotation.java
> +public interface DependencyAnnotation
what is it?
It is not used anywhere.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/ParametricImplementations.java
> +public class ParametricImplementations<T extends ParametricImplementation>
I am not fan of this class name.
`ParametricImplementations` is by convencion class which contains static helpers concerning `ParametricImplementation` class.

Maybe ParametricImplementationGroup would be better? or just ImplementationGroup?

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/annotations/AnnotationHelpers.java
> +public class AnnotationHelpers
Poor name. FunctionHelpers would be better

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                    validateSignaturesCompatibility(genericSignature, implementation.getSignature());
Why signature is part of implementations if we enforce all the implementation have the same. Maybe it should be stored at different level?

Should this also apply to specilizedImplementations or only to ghenericImplementations.

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/MinMaxHelper.java
> +    private static void wrapGenericInteralError(Throwable t)
Internal

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/scalar/annotations/ScalarImplementation.java
>          private final List<Class<?>> argumentNativeContainerTypes = new ArrayList<>();
Change commit message to:

Use interface instead implementing class for field definitions.

2016-11-04 15:42 UTC, losipiuk commented on presto-ml/src/test/java/com/facebook/presto/ml/TestLearnAggregations.java
> +        InternalAggregationFunction aggregation = AggregationFromAnnotationsParser.generateAggregationBindableFunction(
rename `generateAggregationBindableFunction`

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +        checkArgument(stateSerializerFactories.size() == 1, String.format("There must be up to one @AggregationStateSerializerFactory method in class %s for the @AggregationState %s ", aggregationDef
wrap line

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/MinAggregationFunction.java
> +@Description("Returns the minimum value of the argument")
extract

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +                    // This is valid argument but is not part of metadata, binded ealier
syntax of this comment is off

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +            checkArgument(annotations.length > 0, "At least @AggregationState argument is required for each of aggregation functions.");
I think the more readable check would be `method.getParameterCount > 0`

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateAggregationBindableFunction(Class<?> clazz)
rename method

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateAggregationBindableFunction(Class<?> clazz, TypeSignature returnType, List<TypeSignature> argumentTypes)
rename method

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static List<ParametricAggregation> generateBindableAggregationFunctions(Class<?> aggregationDefinition)
rename method

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateBindableAggregationFunction(Class<?> aggregationDefinition)
rename method

2016-11-04 15:42 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/ParametricImplementations.java
> +    public static <T extends ParametricImplementation> ParametricImplementations<T> of(T... implementations)
commit message: from _one_ class

2016-11-07 12:44 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                    validateSignaturesCompatibility(genericSignature, implementation.getSignature());
We only enforce matching (not same) signatures for generic and specialized implementations. There is a generic signature for all implementations but some implementation may have more specialized variants of it. The important bit is that all implementations must match the generic one.

This is abstracted a little bit more to the ParamtericImplementations class in https://github.com/Teradata/presto/pull/396/commits/4f0603b00f88170fbc7ae338c6ca049cd952d8cb#diff-705206c735c150e2452b07142f838e95R115

2016-11-07 12:46 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +            for (Method outputFunction : getOutputFunctions(aggregationDefinition, stateClass)) {
In newer version there is a check by getOnlyElement method to ensure that there is exactly one function like that. We want to fail fast if functions are erratically annotated so no optional here - we just return all we have and throw an exception if it doesn't meet our expectations.

2016-11-07 12:47 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                                aggregationAnnotation.approximate() ? FunctionKind.APPROXIMATE_AGGREGATE : FunctionKind.AGGREGATE,
I've added ensuring that each commit builds to todo list. I will fix that in this step.

2016-11-07 13:08 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +            if (containsMetaParameter(annotations)) {
Wow! Many lambdas, much improvement, wow! ;-)
Done.

2016-11-07 13:13 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationCompiler.java
> +                if (annotation instanceof TypeParameter) {
done

2016-11-07 13:15 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationHeader.java
> +        this.description = description;
done

2016-11-07 13:47 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +    public AggregationImplementation(Signature signature, Class<?> definitionClass, Class<?> stateClass, Method inputFunction, Method outputFunction)
done

2016-11-07 13:49 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementations.java
> +    // These are implementations for when a type parameter binds to a specific native container type
done

2016-11-07 13:52 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementations.java
> +        this.exactImplementations = requireNonNull(exactImplementations);
done

2016-11-07 13:52 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/BindableAggregationFunction.java
> +    AggregationHeader details;
it's intentional an follows ParametricScalar convention

2016-11-07 13:52 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/BindableAggregationFunction.java
> +        return details.getDescription().isPresent() ? details.getDescription().get() : "";
done later

2016-11-07 13:54 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +            checkArgument(annotations.length > 0, "At least @AggregationState argument is required for each of aggregation functions.");
done

2016-11-07 13:57 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationImplementation.java
> +                    // This is valid argument but is not part of metadata, binded ealier
fixed

2016-11-07 13:59 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/metadata/SqlAggregationFunction.java
> +    public static List<SqlAggregationFunction> createFunctionByAnnotations(Class<?> aggregationDefinition)
It's not? Especially in later stages of the code.

2016-11-07 14:00 UTC, fiedukow commented on presto-spi/src/main/java/com/facebook/presto/spi/function/DependencyAnnotation.java
> +public interface DependencyAnnotation
You're right. Removed.

2016-11-07 14:02 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/ParametricImplementations.java
> +public class ParametricImplementations<T extends ParametricImplementation>
Good comment. Renamed.

2016-11-07 14:03 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/annotations/AnnotationHelpers.java
> +public class AnnotationHelpers
FunctionsParserHelper?

2016-11-07 14:04 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/MinMaxHelper.java
> +    private static void wrapGenericInteralError(Throwable t)
fixed

2016-11-07 14:07 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/scalar/annotations/ScalarImplementation.java
>          private final List<Class<?>> argumentNativeContainerTypes = new ArrayList<>();
I don't like this proposition at all, it tells you nothing out of context.

2016-11-07 14:08 UTC, fiedukow commented on presto-ml/src/test/java/com/facebook/presto/ml/TestLearnAggregations.java
> +        InternalAggregationFunction aggregation = AggregationFromAnnotationsParser.generateAggregationBindableFunction(
done later

2016-11-07 14:08 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateAggregationBindableFunction(Class<?> clazz)
done later

2016-11-07 14:08 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateAggregationBindableFunction(Class<?> clazz, TypeSignature returnType, List<TypeSignature> argumentTypes)
done later

2016-11-07 14:08 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static List<ParametricAggregation> generateBindableAggregationFunctions(Class<?> aggregationDefinition)
done

2016-11-07 14:09 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +        checkArgument(stateSerializerFactories.size() == 1, String.format("There must be up to one @AggregationStateSerializerFactory method in class %s for the @AggregationState %s ", aggregationDef
done

2016-11-07 14:09 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/AggregationFromAnnotationsParser.java
> +    public static ParametricAggregation generateBindableAggregationFunction(Class<?> aggregationDefinition)
done

2016-11-07 14:09 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/MinAggregationFunction.java
> +@Description("Returns the minimum value of the argument")
?

2016-11-08 16:38 UTC, losipiuk approved these changes

2016-11-30 12:13 UTC, fiedukow commented
Continued as prestodb PR: https://github.com/prestodb/presto/pull/6627

2016-11-30 12:13 UTC, closed without merging