User revocable memory in HashAggregationOperator
Teradata/presto pull request #397
Opened 2016-10-25 11:05 UTC by pnowojski

2016-10-27 13:28 UTC, losipiuk requested changes

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/Operator.java
> +    default void finishMemoryRevoke()
add javadoc

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/Operator.java
> +    default ListenableFuture<?> startMemoryRevoke()
add some doc that this method cannot touch OperatorContext from spawned threads.

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/Driver.java
> +            getFutureValue(future);
add comment that this is for propagating exception.

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +        if (aggregationBuilder != null) {
consider adding checkState that it is not called again before finishRevoke.

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/builder/InMemoryHashAggregationBuilder.java
> +        return null;
`return CompletableFuture.completedFuture(null);`

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/builder/SpillableHashAggregationBuilder.java
> +        if (!spillInProgress.isDone()) {
shouldn't it be
```
checkState(splillInProgress.isDone());
```

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/builder/SpillableHashAggregationBuilder.java
> +        if (!spillInProgress.isDone()) {
shouldn't it be
```
checkState(splillInProgress.isDone());
```

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +    public ListenableFuture<?> isBlocked()
why is that needed?
It is handled by `Driver.isBlocked(Operator)`

I opt for removing this method from inteface.

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +            this.memoryLimitBeforeSpill = requireNonNull(memoryLimitBeforeSpill, "memoryLimitForMerge is null");
rename variable and argument

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/test/java/com/facebook/presto/operator/OperatorAssertion.java
> +                getFutureValue(operator.startMemoryRevoke());
you may add:
```java
interface Operator {

   default void synchronousMemoryRevoke() {
      getFutureValue(startMemoryRevoke());
      finishMemoryRevoke();
   }
} 
```

and call it here. Not sure if that is worth an effort.

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/testing/TestingTaskContext.java
> +        return createTaskContext(executor, session, maxMemory, preallocated, new DataSize(1, GIGABYTE), new DataSize(1, GIGABYTE));
change commit message to reference TestingTaskContext

2016-10-27 13:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/testing/TestingTaskContext.java
> +        return createTaskContext(executor, session, maxMemory, preallocated, new DataSize(1, GIGABYTE), new DataSize(1, GIGABYTE));
And add commit message and/or comment to explain why is that needed.

2016-10-27 13:28 UTC, losipiuk commented
Some comments. Generally looks good. Tests are kinda hard to follow.

2016-10-28 11:59 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/Operator.java
> +    default ListenableFuture<?> startMemoryRevoke()
done

2016-10-28 11:59 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/Operator.java
> +    default void finishMemoryRevoke()
done

2016-10-28 12:00 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/Driver.java
> +            getFutureValue(future);
done

2016-10-28 12:12 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +            this.memoryLimitBeforeSpill = requireNonNull(memoryLimitBeforeSpill, "memoryLimitForMerge is null");
done

2016-10-28 12:12 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +            this.memoryLimitBeforeSpill = requireNonNull(memoryLimitBeforeSpill, "memoryLimitForMerge is null");
done

2016-10-28 12:15 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +        if (aggregationBuilder != null) {
It's not required in this operator. You could call `startMemoryRevoke` and `finishMemoryRevoke` arbitrary number of times in whatever order you want, so it's a bad place for such a `checkState`

2016-10-28 13:22 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/testing/TestingTaskContext.java
> +        return createTaskContext(executor, session, maxMemory, preallocated, new DataSize(1, GIGABYTE), new DataSize(1, GIGABYTE));
it is used in next commit

2016-10-28 13:23 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java
> +    public ListenableFuture<?> isBlocked()
done

2016-10-28 13:23 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/builder/SpillableHashAggregationBuilder.java
> +        if (!spillInProgress.isDone()) {
done

2016-10-28 13:23 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/builder/SpillableHashAggregationBuilder.java
> +        if (!spillInProgress.isDone()) {
done

2016-11-15 08:31 UTC, closed without merging