dDsl rework readme
Teradata/presto pull request #417
Opened 2016-11-10 21:58 UTC by ebd2

Add a README.md for the plan matching framework.

2016-11-10 22:28 UTC, cawallin approved these changes
Just a few places to clarify, but this looks great

2016-11-10 22:28 UTC, cawallin commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +that needs to be applied for the plan matching framework to functin is likely
function

2016-11-10 22:28 UTC, cawallin commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +#### Fields that produce Symbols
What do you mean by fields? I thought it was fields in the class, but below in your examples you map all of TableScanNode to ColumnReference.

To clarify this, maybe say "PlanNode fields..." in the title and have something like " 'FunctionCall' in 'AggregationNode'" in the table

2016-11-11 15:27 UTC, maciejgrzybek requested changes
Some comments about backticks seem to be outdated since I reviewed commit-by-commit and commented on first commit while you fixed them in second commit. ;)

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +Planner code should be tested by comparing the unoptimized plan to a set of
unoptimized?
It's partially optimized because we test a subset of optimizers.
Otherwise it does not make sense to compare anything. ;)

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +If you want to see examples of basic use of the plan testing framework, look at
I'm not sure if it should be first section in README.
It's sort of _TL;DR_ note.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +TestMergeWindows illustrates both types of tests and goes further into the
Missing backticks.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +There are several things you might want to verify in a PlanNode:
Backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +1. The contents of the PlanNode itself (e.g. equi criteria in a JoinNode)
ditto

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +2. The contents of some Symbol-producing member of the PlanNode (e.g.
ditto

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +These should be handled separately.
This implies to me that Rvalue Matching should be handled in separate test from NodeMatchers.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +an object's own .equals method rather than implementing the comparison itself.
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +See JoinMatcher for an example of comparing non-symbol producing fields.
ditto

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +Fields that produce Symbols should be compared with an RvalueMatcher that can
ditto

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +TableScanNode | ColumnReference
I think it's quite confusing at this place.
Not enough introduction for such detailed info.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +At a high level, Presto plans represent data through Symbols. A TableScanNode,
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +
I'd mention symbol tracking through aliases here, not earlier. So maybe you can move https://github.com/Teradata/presto/pull/417/commits/c43c467cb9e875870cdade078253a0c0cfadb5e4#diff-08700b6c8524843d8b16847b73536343R62 somehow here?

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +`SELECT name FROM people` query has an OutputNode with an output symbol that
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +In order for the plan testing framework to be independent of how Presto
I'd say that Symbols might be renamed throughout a query, thus it's important to keep track of their origins, so you can bind places with the same data expected.
Mentioning symbol allocation is a bit too low level as for README IMO.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +Binding the alias to the Symbol where it originates must also be independent of
I'd skip this sentence.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +As an example, take a TableScanNode:
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +`with()`. This would be cumbersome. In practice, any non-trivial node should
I don't think it's really necessary (part of how to write a `static` method).
It's too low level detail while we can catch that on review if one does not express his Alias Matching clearly.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +`with()`. This would be cumbersome. In practice, any non-trivial node should
Also, existing DSL tests are great example, so I believe anyone writing DSL tests would follow patterns found there.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +the OutputNode contains a symbol that represents the `name` column. For more complex fields in PlanNodes, this isn't generally the case.
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +for the OutputNode can use the bound alias `NAME_ALIAS` directly to verify that
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +In the above example, the Matcher that output() adds to the `PlanMatchPattern`
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +In the above example, the Matcher that output() adds to the `PlanMatchPattern`
Don't refer to snippet from previous section.

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +In the above example, the Matcher that output() adds to the `PlanMatchPattern`
Also it looks to me it does not fit here (how's that correspond to `ExpectedValueProvider`?).

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +Expected values actually have to be created once the aliases of the direct and
Shouldn't this be the first paragraph of `ExpectedValueProviders` section?

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +ExpectedValueProvider.
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +An implementation of `ExpectedValueProvider<T>` should hold the values and
How about creating a section **best practices** to put it there along with https://github.com/Teradata/presto/pull/417/commits/c43c467cb9e875870cdade078253a0c0cfadb5e4#diff-08700b6c8524843d8b16847b73536343R117 (`static` method)?

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +a value for that field to T's constuctor, using an ExpectedValueProvider that
backticks

2016-11-11 15:27 UTC, maciejgrzybek commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +understands SymbolAliases directly likely causes tests to pass erroneously
Clarify that it's easy to diverge tests from actual code.

2016-11-11 15:39 UTC, cawallin commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +If you want to see examples of basic use of the plan testing framework, look at
eh, TL;DR seems reasonable for a README intro. that's the point of intros ;)

2016-11-11 16:20 UTC, ebd2 commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +Planner code should be tested by comparing the unoptimized plan to a set of
*Should* be, in a perfect world. Can't be for reasons subsequently explained...

2016-11-11 16:22 UTC, ebd2 commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +An implementation of `ExpectedValueProvider<T>` should hold the values and
I'm not sure this is a best-practice per-se, so much as intrinsic to how they need to work. Is there some other possible way I'm missing?

2016-11-11 16:25 UTC, ebd2 commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/README.md
> +These should be handled separately.
How about "Matching these in a test requires two different approaches."

2016-11-11 19:50 UTC, closed without merging