JBOD support for spiller
Teradata/presto pull request #422
Opened 2016-11-14 14:39 UTC by losipiuk

2016-11-15 12:37 UTC, pnowojski requested changes

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/SingleStreamSpillerBasedSpiller.java
> +public class SingleStreamSpillerBasedSpiller
`GenericSpiller`?

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +/*
move this commit before `Introduce SingleStreamSpillerBasedSpiller`

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/SingleStreamSpillerBasedSpiller.java
> +        singleStreamSpillers.forEach(closer::register);
oO

`singleStreamSpillers.forEeach(SingleStreamSpiller::close);`

or add them to closer upon creation and use closer as field in this class.

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +        closer.register(() -> Files.delete(targetFileName));
why do you keep registering in close methods instead of closing directly? It adds complexity of using closer class without any of it's benefits.

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +        try (SliceOutput output = new OutputStreamSliceOutput(new BufferedOutputStream(new FileOutputStream(targetFileName.toFile(), true)))) {
this contract is weird. Consecutive calls to `SingleStreamSpiller::spill` will overwrite file which makes interface of that class weird, counter intuitive and is undocumented "feature". Especially call `SingleStreamSpiller::spill(Page page)` doesn't make any sense. 

Implement it in a way that supports more then one call `spill(...)`. Alternative is to pass `pageIterator` in constructor, but it's also ugly and "wtf" candidate.

What's more, it will not work for spilling in joins.

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/LocalSpillContext.java
> +import java.io.Closeable;
again wrong order of commits. This should be before `Introduce BinaryFileSingleStreamSpiller`

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/OnePathBinaryFileSingleStreamSpillerFactory.java
> +public class OnePathBinaryFileSingleStreamSpillerFactory
What's the purpose of this class? It's name is really bad.

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/MultiPathBinaryFileSingleStreamSpillerFactory.java
> +public class MultiPathBinaryFileSingleStreamSpillerFactory
? Why this is added in separate commit that overrides previous one?

Why do you have to include in class name implementation detail? Does the user of this class care whether spills are written to one or multiple paths? Just name it `BinaryFileSingleStreamSpillerFactory`

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/MultiPathBinaryFileSingleStreamSpillerFactory.java
> +        int startIndex = roundRobinIndex.incrementAndGet();
if disks 1 to 6 are full (out of 10 disks total), `roundRobinIndex` is 1, there won't be any concurrency for 6 consecutive writes. This both decreases performance and increases chance of this overloaded disk running out of space. Can you remember last successfully chosen `roundRobinIndex`?

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
single spill can easily exceed 1GB

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
maybe set this value to query.max-memory-per-node?

2016-11-15 12:37 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/metadata/Metadata.java
> +    List<TableLayoutResult>  getLayouts(Session session, TableHandle tableHandle, Constraint<ColumnHandle> constraint, Optional<Set<ColumnHandle>> desiredColumns);
white space

2016-11-15 14:48 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/SingleStreamSpillerBasedSpiller.java
> +        singleStreamSpillers.forEach(closer::register);
done

2016-11-15 14:51 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/SingleStreamSpillerBasedSpiller.java
> +public class SingleStreamSpillerBasedSpiller
done

2016-11-15 15:08 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +        try (SliceOutput output = new OutputStreamSliceOutput(new BufferedOutputStream(new FileOutputStream(targetFileName.toFile(), true)))) {
It will not overwrite. It will append data to file. Is that wrong?
I have test for that.

2016-11-15 15:10 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/LocalSpillContext.java
> +import java.io.Closeable;
It is actually.

2016-11-15 15:30 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/MultiPathBinaryFileSingleStreamSpillerFactory.java
> +        int startIndex = roundRobinIndex.incrementAndGet();
I changed the `getNextSpillPath` to be synchronized and single call to it changes the `roundRobinIndex` to point to first spillPath after one which was picked.

2016-11-15 15:31 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
I can change that.

I think now that there still be issue as we do not count spills in progress as allocated disk space.
Maybe we can ignore that for now. What do you think?

2016-11-15 15:53 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
Well actually I cannot change that. It seems that there is no mechanism for configs depending on other configs. @Inject does not work.

2016-11-15 15:55 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/metadata/Metadata.java
> +    List<TableLayoutResult>  getLayouts(Session session, TableHandle tableHandle, Constraint<ColumnHandle> constraint, Optional<Set<ColumnHandle>> desiredColumns);
done

2016-11-15 16:04 UTC, losipiuk commented
addressed addressable comments

2016-11-15 16:04 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/LocalSpillContext.java
> +import java.io.Closeable;
And - why "again". Was there another such comment?

2016-11-16 06:33 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +        try (SliceOutput output = new OutputStreamSliceOutput(new BufferedOutputStream(new FileOutputStream(targetFileName.toFile(), true)))) {
Ops, if that's the default behavior then it's fine

2016-11-16 06:34 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/LocalSpillContext.java
> +import java.io.Closeable;
yes, there is one commit that you didn't address before that.

Maybe you pushed them to github in wrong order?

2016-11-16 06:34 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +/*
bump

2016-11-16 06:36 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
So maybe default value 90% would be better?

2016-11-16 06:36 UTC, pnowojski commented
please address non addressed comments

2016-11-16 10:55 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/OnePathBinaryFileSingleStreamSpillerFactory.java
> +public class OnePathBinaryFileSingleStreamSpillerFactory
renamed and squashed

2016-11-16 10:55 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/MultiPathBinaryFileSingleStreamSpillerFactory.java
> +public class MultiPathBinaryFileSingleStreamSpillerFactory
squashed

2016-11-16 12:12 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private DataSize spillMinimumFreeSpaceThreshold = DataSize.succinctDataSize(1, DataSize.Unit.GIGABYTE);
done

2016-11-16 12:13 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +        closer.register(() -> Files.delete(targetFileName));
So I do not have to take care of exception handling.

2016-11-16 12:17 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/BinaryFileSingleStreamSpiller.java
> +/*
It was fine. Probably order on github was messed up.

2016-11-16 12:20 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/spiller/MultiPathBinaryFileSingleStreamSpillerFactory.java
> +public class MultiPathBinaryFileSingleStreamSpillerFactory
squashed

2016-11-16 12:30 UTC, pnowojski approved these changes

2016-11-16 12:30 UTC, pnowojski commented on presto-main/src/main/java/com/facebook/presto/spiller/SingleStreamSpillerBasedSpillerFactory.java
> +public class SingleStreamSpillerBasedSpillerFactory
`GenericSpillerFactory`?

2016-11-16 15:02 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/spiller/SpillerStats.java
>      public long getTotalSpilledBytes()
It would probably make sense for the other stats that I added to be here in SpillerStats, too.

2016-11-16 15:14 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/spiller/SpillerStats.java
>      public long getTotalSpilledBytes()
Nevermind, I see that SpillerStats are global.

2016-11-22 13:10 UTC, closed without merging