Document optimizer for choose join distribution
Teradata/presto pull request #424
Opened 2016-11-16 21:57 UTC by rschlussel

Add documentation about the choice between replicated and partitioned
joins.

The PR with the feature is still under review, but I started work on the documentation.

2016-11-16 22:24 UTC, kbajda requested changes
Some minor comments to make the description more generic.
Also, additional changes communicated in-person.

2016-11-16 22:24 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +as it requires less memory on each node. However, it can be much slower than replicated joins because it can require more data to be transferred
"less memory on each node" AND allows Presto to handle bigger joins overall.

2016-11-16 22:24 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +as it requires less memory on each node. However, it can be much slower than replicated joins because it can require more data to be transferred
"it can require" -> "it typically requires"

2016-11-16 22:24 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +In a replicated join, the input on the right side is distributed to all of the nodes on the cluster containing data from the input on the left.
"the input on the right side" -> "the smaller table"

2016-11-16 22:29 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +In a replicated join, the input on the right side is distributed to all of the nodes on the cluster containing data from the input on the left.
that's only true when we use `join-distribution-type=automatic`.  Otherwise it's always the right table.

2016-11-17 00:47 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +Presto can perform two types of distributed joins: partitioned and replicated.
is it partitioned or re-partitioned?

2016-11-17 00:47 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +as it requires less memory on each node. However, it can be much slower than replicated joins because it can require more data to be transferred
I would say first explain both the types and then come to pros and cons of each type.

2016-11-17 00:47 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +the session property ``join_distribution_type``
may be give the set session command

2016-11-17 00:47 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +to determine its size, a partitioned join is performed. If ``join-reordering-enabled`` is set to ``true``, then Presto will look at both the left input and the right
Put the join-reordering-enabled on a new line as it is a new property being introduced.

2016-11-17 16:30 UTC, rschlussel-zz commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +Presto can perform two types of distributed joins: partitioned and replicated.
Aren't they the same thing?  But I can use repartitioned instead

2016-11-17 16:30 UTC, rschlussel-zz commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +to determine its size, a partitioned join is performed. If ``join-reordering-enabled`` is set to ``true``, then Presto will look at both the left input and the right
Changed the behavior, so not relevant anymore.

2016-11-17 16:30 UTC, rschlussel commented
Addressed comments

2016-11-17 20:07 UTC, kbajda approved these changes

2016-11-22 16:04 UTC, kbajda requested changes

2016-11-22 16:04 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +original join order as much as possible.
Maybe clarify what if no reordering is possible to avoid cross join(s). Would the order of joins change at all?

2016-11-22 16:04 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +in query plan and try to eliminate them by changing order of the joins. While doing so optimizer will try to preserve
Please clarify that this reordering is done without looking at any table stats at this point.

2016-11-22 16:04 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +Join order will change from ``part, orders, lineitem, supplier, nation`` to ``part, lineitem, orders, supplier, nation``.
Please add a "Note: the same can be achieved by manually changing the order of tables in the query". Just in case it's not obvious for some users :)

2016-11-22 17:56 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +Partitioned and Replicated Joins
Change this to Repartitioned

2016-11-22 17:56 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/join-distribution-type.rst
> +``partitioned``, ``replicated``, and ``automatic``. The default value is ``partitioned``. The property can also be set per session using
shouldn't this be called repartitioned?

2016-11-23 08:05 UTC, pnowojski commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +in query plan and try to eliminate them by changing order of the joins. While doing so optimizer will try to preserve
done

2016-11-23 08:05 UTC, pnowojski commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +original join order as much as possible.
done

2016-11-23 08:05 UTC, pnowojski commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +Join order will change from ``part, orders, lineitem, supplier, nation`` to ``part, lineitem, orders, supplier, nation``.
done

2016-11-25 15:39 UTC, kbajda approved these changes

2016-11-25 19:25 UTC, rschlussel commented
Closing. I've squashed fixups together, and made some grammatical changes. I'm going to open a new pr that combines mine and @pnowojski work along with documentation for optimizing without statistics.

2016-11-25 19:25 UTC, closed without merging