Add doc for statistics
Teradata/presto pull request #437
Opened 2016-11-22 13:42 UTC by losipiuk

2016-11-22 14:32 UTC, fiedukow commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> + * ``SHOW STATS FOR (SELECT <column_list|*> FROM <table_name> WHERE <filtering_condition>`` -
closing bracket missing

2016-11-22 16:36 UTC, kbajda requested changes
Some minor comments.
How about moving this content under the "optimizer" doc section introduced in https://github.com/Teradata/presto/pull/424/ ?

2016-11-22 16:36 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> +Table statistics can be displayed via Presto CLI using ``SHOW COLUMN STATS`` command.
"COLUMN" is obsolete

2016-11-22 16:36 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> +Cost in EXPLAIN
I would make it a separate subsection.

2016-11-24 14:49 UTC, losipiuk commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> +Cost in EXPLAIN
sure

2016-11-24 14:49 UTC, losipiuk commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> + * ``SHOW STATS FOR (SELECT <column_list|*> FROM <table_name> WHERE <filtering_condition>`` -
done

2016-11-24 14:49 UTC, losipiuk commented on presto-docs/src/main/sphinx/statistics/statistics.rst
> +Table statistics can be displayed via Presto CLI using ``SHOW COLUMN STATS`` command.
done

2016-11-24 14:50 UTC, losipiuk commented
> Some minor comments.
> How about moving this content under the "optimizer" doc section introduced in #424/ ?

Moved

2016-11-24 15:02 UTC, losipiuk commented
addressed comments

2016-11-24 15:02 UTC, losipiuk commented
@KBP-TDC please remove changes-requested tag if it is ok now.

2016-11-25 15:48 UTC, kbajda approved these changes

2016-11-28 10:49 UTC, losipiuk commented
merged

2016-11-28 10:49 UTC, closed without merging