Document current rule based optimizer
Teradata/presto pull request #445
Opened 2016-11-26 01:05 UTC by akshatnair

Add a section that gives an explanation of various steps involved
in creating a logical plan.

2016-11-28 16:56 UTC, rschlussel-zz requested changes

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Each of the node classes in this logical plan are derived from PlanNode. Base logical plan is then
I think since these are user docs and not developer docs, we don't care that it's derived from PlanNode.

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Consider this example,
colon not comma at the end

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +For this query Presto will generate a logical base plan,
ditto

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +optimized using list of optimizer transformation rules like PredicatePushDown or PruneUnreferencedOutputs
a list

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Logical plan is then fragmented into sub-plans that can be shipped for execution to distributed nodes.
Talk explicitly about physical planning.

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +to get the final logical plan. Various transformations that are currently applied can be
Maybe walk through an example of a rule and how it changes the plan (i.e. what the plan was before vs. after the rule and why)

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +query and if they conform to the given rules. Next step is semantic analysis which
The next step is semantic analysis, which gathers the semantic information from the query that is necessary for planning.  It deals with things like type checking and verifying that the column names used in the query exist for a given table.

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Syntax analysis or parsing is used to determine various structures in the given
Syntactic analysis, or parsing, is used to break down the query into its component structures and check that the query conforms to the syntactic rules of SQL.

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Each of the node classes in this logical plan are derived from PlanNode. Base logical plan is then
The base logical plan

2016-11-28 16:56 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +found in class `presto-main/src/main/java/com/facebook/presto/sql/planner/PlanOptimizers.java`.
I think this is also too low level for user docs.

2016-11-28 21:35 UTC, petroav commented
@KBP-TDC can you take a look at this and let us know if you had something else in mind?

2016-11-28 21:40 UTC, ebd2 commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Each of the node classes in this logical plan are derived from PlanNode. Base logical plan is then
Also, grammar nit: "of the node classes in this logical plan" is a prepositional phrase, and does not affect the pluralness of "Each", which is singular. It should read Each ... is derived from ....

2016-11-28 21:58 UTC, KBP-TDC commented
I agree with Rebecca's comments. The intended audience is customer DBA-type folks and our PS/ThinkBig. They don't know or care about Presto source code. They likely know general DBMS/SQL tuning stuff and want to reason about Presto performance tuning and how analyze & speedup performance. They will look at EXPLAIN plans, Presto Live Query plan, order of joins, etc. Giving them background on how current Presto Optimizer works (rule-based + list a few important rule optimizations, syntactic order of joins) so they can understand better what's going on, it's sufficient.

2016-11-28 23:48 UTC, akshatnair commented
I will update it to be more DBA friendly

2016-11-29 01:05 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Syntax analysis or parsing is used to determine various structures in the given
done

2016-11-29 01:05 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +query and if they conform to the given rules. Next step is semantic analysis which
done

2016-11-29 01:05 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Consider this example,
done

2016-11-29 01:05 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +For this query Presto will generate a logical base plan,
done

2016-11-29 01:08 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +optimized using list of optimizer transformation rules like PredicatePushDown or PruneUnreferencedOutputs
done

2016-11-29 01:09 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +found in class `presto-main/src/main/java/com/facebook/presto/sql/planner/PlanOptimizers.java`.
done

2016-11-29 01:09 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Logical plan is then fragmented into sub-plans that can be shipped for execution to distributed nodes.
done

2016-11-29 02:05 UTC, akshatnair commented
@rschlussel @KBP-TDC updated

2016-11-29 17:13 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +analysis, semantic analysis, logical plannning, physical planning and then execution.
plannning -> planning

2016-11-29 18:39 UTC, rschlussel-zz reviewed
It's a good overview of what happens in the planner, but possibly still too much from a developer perspective than a dba/user perspective-- I'm not sure where the line is on that.  I'd wait for @KBP-TDC to comment before merging.

2016-11-29 18:39 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +`PredicatePushDown` or `PruneUnreferencedOutputs` to get the final logical plan. For example consider
Instead of using class names, describe some of the key optimizations here.

2016-11-29 18:39 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Presto currently has a rule based optimizer. A given SQL query goes through syntactic
I think @KBP-TDC  was saying that even talking about all these different stages was more low level than users need.   Maybe he can give a more specific description of what he's looking for or if  this is good.

2016-11-29 18:44 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Presto currently has a rule based optimizer. A given SQL query goes through syntactic
he seems to have reviewed it

2016-11-29 18:46 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +`PredicatePushDown` or `PruneUnreferencedOutputs` to get the final logical plan. For example consider
ok

2016-11-29 18:46 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/logical-planner.rst
> +Presto currently has a rule based optimizer. A given SQL query goes through syntactic
great, then looks good to me.

2016-11-29 19:42 UTC, KBP-TDC commented
I think we should merge this. We will improve as things develop.
Once we have the whole section wrapped up, we can get some "external" reviewers who are closer to the end users to get their feedback as well.

2016-11-30 01:46 UTC, closed without merging