Do not use planner in SHOW STATS implementation
Teradata/presto pull request #474
Opened 2016-12-16 16:58 UTC by losipiuk

2016-12-16 17:15 UTC, ArturGajowy requested changes
LGTM modulo comments

2016-12-16 17:15 UTC, ArturGajowy commented on presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java
> +            // analyze statement
Extract methods instead of using comments :)

2016-12-16 17:15 UTC, ArturGajowy commented on presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java
> +            final Map<QualifiedNameReference, Symbol> symbolMap = new HashMap<>();
drop the final, it's not used elsewhere (the keyword)

2016-12-16 17:15 UTC, ArturGajowy commented on presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowStatsRewrite.java
> +            TupleDomain<ColumnHandle> columnTupleDomain = symbolTupleDomain.transform(symbol -> columnHandles.get(symbol.getName()));
The column handles seem to be used only here. Move the declaration as close as possible to the usage.

2016-12-19 06:25 UTC, kokosing approved these changes

2016-12-19 16:46 UTC, losipiuk commented
After offline discussion with beloved @fiedukow I decided to kill this PR.

2016-12-19 16:46 UTC, closed without merging