Fix Simba specific JDBC tests
Teradata/presto pull request #486
Opened 2017-01-17 17:51 UTC by brian-rickman

Adjust tests to accomodate recent changes in data types
and metadata.

2017-01-17 17:57 UTC, cawallin requested changes

2017-01-17 17:57 UTC, cawallin commented on presto-product-tests/src/main/resources/com/facebook/presto/tests/jdbc/get_nation_columns_simba.result
> +hive|default|nation|n_name|12|varchar(25)|25|25|null|10|1|null|null|null|null|2048|2|YES|null|null|null|null|null|null|
is varchar(25) what is supposed to be printed out for this metadata? or is it varchar with a separate field being 25 (precision)?

2017-01-17 17:57 UTC, cawallin commented on presto-product-tests/src/main/resources/com/facebook/presto/tests/jdbc/get_nation_columns_simba4.result
> +hive|default|nation|n_name|12|varchar(25)|25|25|null|10|1|null|null|null|null|2048|2|YES|null|null|null|null|null|
ditto on varchar(25)

2017-01-17 19:44 UTC, brian-rickman commented on presto-product-tests/src/main/resources/com/facebook/presto/tests/jdbc/get_nation_columns_simba4.result
> +hive|default|nation|n_name|12|varchar(25)|25|25|null|10|1|null|null|null|null|2048|2|YES|null|null|null|null|null|
That is coming from Presto.  We see the same value with the open source JDBC driver.  I'm not sure why it was changed from `varchar`, but my reading of the docs is that either value is valid:

[JDBC spec](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)) says:
> TYPE_NAME String => Data source dependent type name, for a UDT the type name is fully qualified
> COLUMN_SIZE int => column size.

2017-01-17 19:46 UTC, cawallin approved these changes

2017-01-17 19:58 UTC, merged

2017-01-23 21:15 UTC, brian-rickman commented
Adding the changes from #489 to this branch as they are closely related.