Add docs and additional tests
Teradata/presto pull request #503
Opened 2017-02-13 21:51 UTC by sanjay990

This commit adds docs and additional java based tests for SQL Server.

2017-02-13 22:17 UTC, akshatnair commented
Looks good, most of it seems pretty similar to MySQL.

2017-02-13 22:53 UTC, sanjay990 commented
@akshatnair : Yep, its almost same, though we don't have negative and data type tests for other JDBC based connectors.

2017-02-13 23:01 UTC, brian-rickman commented
LGTM

2017-02-13 23:20 UTC, maciejgrzybek requested changes
Also, please squash 01090b1f873a3ff73ba983e5e86e0d9d1cc887cc with 2fa2b4a4b7ce3b894e035cdcf26cac35b3f40afe

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +or want to connect to multiple SQL Server servers, you must configure
_want to connect to multiple instance of the SQL Server_

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +multiple instances of the SQL Server connector.
`catalogs` instead of `instances of the connector`?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +if you name the property file ``sales.properties``, Presto will create a
It's nothing SQL server specific. Shouldn't we refer to the general Presto docs here?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +The SQL Server connector provides a schema for every SQL Server schema.
Maybe something like: "_The SQL Server connector provides access to all schemas visible to the specified user in configured database._"?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +    SHOW SCHEMAS FROM sqlserver;
Again, isn't it too generic?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +    SHOW SCHEMAS FROM sqlserver;
Also, you don't refer name `sqlserver`. You should say e.g. "for SQL Server catalog named _sqlserver_ this would be:"

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +If you have a SQL Server schema named ``web``, you can view the tables
_SQL Server_ is unnecessary.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +Finally, you can access the ``clicks`` table in the ``web`` schema::
Why you recognize _access_ to be _select_ only?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +If you used a different name for your catalog properties file, use
`sqlserver` catalog name should be mentioned before.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +float
Shouldn't we mention the difference / lack of difference between `float` and `real`?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +text
What type we translate `text` into? I believe we should have this explained with any details whenever they're relevant. E.g. I'd picture this as a table:
SQL Server type | Presto type
float double
real float

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidTable()
s/Invalid/NonExistent/

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidSchema()
Ditto

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidColumn()
Ditto

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                immutableTable(NATION)
Unnecessary newlines.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                CONNECTOR_NAME,
Extract `format("%s.%s.%s", CONNECTOR_NAME, KEY_SPACE, NATION.getName())` to constant and reuse it in all tests here instead of copy&pasting.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +    public void testNationJoinNation()
`testNationSelfInnerJoin`

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        return compose(
Do we need a `compose` here?
You didn't use it here: https://github.com/Teradata/presto/pull/503/commits/01090b1f873a3ff73ba983e5e86e0d9d1cc887cc#diff-96992044a8263d5b64ebe0e853fcb3b3R40

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +}
Add a test for pushdown (`where` clause).
Also for aggregates (e.g. `count(1)`) because we've seen issues with them previously in other connectors.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
>          );
Wrong formatting.

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                                Timestamp.valueOf("0001-01-01 00:00:00.000"), Timestamp.valueOf("1900-01-01 00:00:00")),
Is it properly defined by JDBC standard what's the expected value for such a date?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                        row(Long.MAX_VALUE, Short.MAX_VALUE, Integer.MAX_VALUE, Byte.MAX_VALUE, Double.MAX_VALUE,
How about the test of parametrized `float`?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/SqlServerDataTypesTableDefinition.java
> +                    "c char(4), vc varchar(4), te text, nc nchar(4), nvc nvarchar(4), nt text," +
Why all of precision 4 only?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/SqlServerDataTypesTableDefinition.java
> +                            Date.valueOf("9999-12-31"), Timestamp.valueOf("9999-12-31 23:59:59.997"),
Are you sure you want to rely on the `Timestamp.valueOf()` for non-standard timestamps?
Is the behavior of `Timestamp.valueOf()` in such a case what we want to expect from that connector?

2017-02-13 23:20 UTC, maciejgrzybek commented on presto-product-tests/README.md
> +Note: SQL Server product-tests use `microsoft/mssql-server-linux` docker container. We assume you accept the license
I don't know how it should sound from the legal perspective but "we assume" does not sound good to me. Maybe "By running sql server product tests you accept the license ..." is better? Or someone with actual legal knowledge should take a stand here?

2017-02-14 15:15 UTC, sanjay990 commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +Finally, you can access the ``clicks`` table in the ``web`` schema::
This is a generic which we use for all JDBC based connectors.
What else do you plan to include.

2017-02-14 15:19 UTC, sanjay990 commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +If you used a different name for your catalog properties file, use
didn't get this

2017-02-14 15:20 UTC, sanjay990 commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +float
Rather than explaining the difference between different SQL Server data types. I can provide a link for the same.

2017-02-14 17:35 UTC, sanjay990 commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +    SHOW SCHEMAS FROM sqlserver;
I think its fine to have it here as an example. In case, you want I can provide a link to `show schemas`

2017-02-14 18:50 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        return compose(
Yes, its needed if we need to create multiple tables.

2017-02-14 19:03 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                                Timestamp.valueOf("0001-01-01 00:00:00.000"), Timestamp.valueOf("1900-01-01 00:00:00")),
This is supported by respective SQL Server data type. For e.g. for date
`0001-01-01 through 9999-12-31 `
https://msdn.microsoft.com/en-us/library/bb630352.aspx

2017-02-14 19:06 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/SqlServerDataTypesTableDefinition.java
> +                    "c char(4), vc varchar(4), te text, nc nchar(4), nvc nvarchar(4), nt text," +
I wanted to test with some arbitrary, just took 4.

2017-02-14 19:09 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidTable()
57e4fb11d7877a38d0f5852c125a21e2db2dd2cb

2017-02-14 19:09 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidSchema()
57e4fb11d7877a38d0f5852c125a21e2db2dd2cb

2017-02-14 19:09 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/NegativeTests.java
> +    public void testInvalidColumn()
57e4fb11d7877a38d0f5852c125a21e2db2dd2cb

2017-02-15 18:45 UTC, sanjay990 commented
@maciejgrzybek : Incorporated your comments. 
I will merge data type and java tests commits after your LGTM :)

2017-02-15 21:01 UTC, maciejgrzybek requested changes

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-docs/src/main/sphinx/connector/sqlserver.rst
> +or want to connect to multiple instance of the SQL Server, you must configure
`instances`

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        );
Wrong formatting (put ")" in the end of previous line).

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        );
ditto formatting

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        );
ditto

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/cassandra/NegativeTests.java
>      @Test(groups = CASSANDRA)
Why did you change cassandra tests while it's sql server PR?

2017-02-15 21:01 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                                Double.valueOf("1234567891234567"), Float.valueOf("12345678")
Why don't you use any fraction numbers?
Integers up to 2^24 can be precisely expressed by float (and up to 2^53 for doubles) IIRC.

2017-02-15 22:00 UTC, maciejgrzybek commented on presto-sqlserver/src/main/java/com/facebook/presto/plugin/sqlserver/SqlServerClient.java
> +                .append(singleQuote(handle.getCatalogName(), handle.getSchemaName(), handle.getTemporaryTableName()))
Why? How is it related?

2017-02-15 22:00 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/cassandra/NegativeTests.java
> +    public void testInvalidTable()
You could simply revert your previous fixup ;)

2017-02-15 22:03 UTC, sanjay990 commented on presto-sqlserver/src/main/java/com/facebook/presto/plugin/sqlserver/SqlServerClient.java
> +                .append(singleQuote(handle.getCatalogName(), handle.getSchemaName(), handle.getTemporaryTableName()))
Its for CTAS, this was a bug which is fixed now.

2017-02-15 22:08 UTC, maciejgrzybek approved these changes

2017-02-16 01:02 UTC, closed without merging