Add new profile for SQL Server
Teradata/presto pull request #504
Opened 2017-02-21 15:26 UTC by sanjay990

2017-02-21 15:26 UTC, sanjay990 commented
I'll probably merge these commits with existing commits.

2017-02-21 16:49 UTC, ArturGajowy requested changes

2017-02-21 16:49 UTC, ArturGajowy commented on presto-product-tests/conf/docker/singlenode-sqlserver/docker-compose.yml
> +version: '2'
move the sqlserver container from standard.yml to here

2017-02-21 16:49 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  EXTERNAL_SERVICES="hadoop-master cassandra sqlserver"
add a comment why cassandra is needed here

2017-02-21 16:50 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  EXTERNAL_SERVICES="hadoop-master cassandra sqlserver"
the comment should link to a tempto issue that - once solved - will allow us to not have cassandra here. If there's not such an issue, create it.

2017-02-21 18:22 UTC, sanjay990 commented on presto-product-tests/conf/docker/singlenode-sqlserver/docker-compose.yml
> +version: '2'
@ArturGajowy https://github.com/Teradata/presto/pull/504/commits/ab6a78fd88af3561cbe091ad77e69b7cddcc716a

2017-02-22 14:27 UTC, ArturGajowy commented
fixup looks good!

2017-02-22 14:28 UTC, ArturGajowy approved these changes

2017-02-22 16:03 UTC, sanjay990 commented
Merged

2017-02-22 16:03 UTC, closed without merging