Add Create Table As Select test for SQL Server
Teradata/presto pull request #515
Opened 2017-03-06 20:00 UTC by sanjay990

2017-03-06 20:18 UTC, maciejgrzybek requested changes

2017-03-06 20:18 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        assertThat(queryResult).matches(PRESTO_NATION_RESULT);
Drop the table, you have just created, when the test finished.

2017-03-07 15:45 UTC, sanjay990 commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        assertThat(queryResult).matches(PRESTO_NATION_RESULT);
https://github.com/Teradata/presto/pull/515/commits/6a50b4b6418045823d5f239928e6404302d745fd

2017-03-07 16:00 UTC, rschlussel commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +                "CREATE TABLE %s AS SELECT * FROM %s", CREATE_TABLE_AS_SELECT, NATION_TABLE_NAME);
I don't think you mean to create it again too.

2017-03-07 17:54 UTC, maciejgrzybek requested changes

2017-03-07 17:54 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        onPresto().executeQuery(format("DROP TABLE IF EXISTS %s", CREATE_TABLE_AS_SELECT));
This won't be triggered if previous queries fail. You need some sort of final-block but without hiding the reason for an actual failure. Have a look how we have this done in `AbstractTestHiveClient` (method `dropTable`). Or, similar approach in `AlterTableTests`, with `dropTestTables` method.

2017-03-07 19:03 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +        sql = format(
I believe you should not use Presto to check results.
It's like using a test subject for the test itself.

How hard would it be to introduce `onSqlServer().executeQuery(...)`?

2017-03-08 16:25 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/hive/TestGrantRevoke.java
> +        extends ProductTest
Is the formatting off here?

2017-03-08 16:27 UTC, maciejgrzybek commented on presto-product-tests/src/main/java/com/facebook/presto/tests/sqlserver/Select.java
> +    private static final String CTAS = "create_table_as_select";
CTAS_TABLE_NAME

2017-03-08 16:27 UTC, maciejgrzybek approved these changes

2017-03-08 16:28 UTC, maciejgrzybek commented
Looks good. Two nits mentioned.

Make sure Travis passes, though!

2017-03-08 19:33 UTC, closed without merging