Access control enabled roles
Teradata/presto pull request #519
Opened 2017-03-10 23:16 UTC by arhimondr

2017-03-10 23:20 UTC, arhimondr commented
@amrutagokhale I think you should cherry-pick `Remove access control for show grants` and `	Remove grantee parameter from show grants signature` to `SHOW GRANTS` Pull request

2017-03-14 16:15 UTC, amrutagokhale commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
>      {
Is it true that the `admin` role has GRANT OPTION implicitly assigned to it? Do the Hive specs say so?

2017-03-14 16:15 UTC, amrutagokhale commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
> +            boolean grantOptionRequired)
Can we combine the two arguments -- `HivePrivilege requiredPrivilege` and `boolean grantOptionRequired` into an object of type `HivePrivilegeInfo` and pass that instead?

2017-03-14 23:03 UTC, amrutagokhale approved these changes

2017-03-14 23:08 UTC, cawallin requested changes
I'm almost done but not quite (I've reviewed all but the last three commits)

2017-03-14 23:08 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/HivePrivilegeInfo.java
> +                throw new IllegalArgumentException("Unexpected privilege: " + privilege);
Should this be a categorized exception?

2017-03-14 23:08 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
> +            boolean grantOptionRequired)
Or create two methods, something like checkTablePermission() and checkTablePermissionWithGrantOptionRequired()

2017-03-14 23:08 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
>      @Override
I think that the commit message for  Refactor canCreateView security checks is wrong. I'm not really sure what you're trying to say :)

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/metadata/Metadata.java
>       * Gets the privileges for the specified table available to the given grantee
adjust the comment to talk about the session user

2017-03-14 23:08 UTC, cawallin commented on presto-spi/src/main/java/com/facebook/presto/spi/connector/ConnectorMetadata.java
>       * List the table privileges granted to the specified grantee for the tables that have the specified prefix
ditto on changing the javadoc

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/server/HttpRequestSessionFactory.java
> +        identity = new Identity(user, Optional.ofNullable(servletRequest.getUserPrincipal()), parseRoleHeaders(servletRequest));
Is this a Simba-visible change or only an internally-visible change?

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/Session.java
> +                identity.getRoles(),
do you still need to pass roles separately into FullConnectorSession?

2017-03-14 23:08 UTC, cawallin commented on presto-spi/src/main/java/com/facebook/presto/spi/security/Identity.java
> +    public Identity(String user, Optional<Principal> principal, Map<String, SelectedRole> roles)
Fantastic change :+1:

2017-03-14 23:08 UTC, cawallin commented on presto-spi/src/main/java/com/facebook/presto/spi/security/Identity.java
> +        sb.append(", roles=").append(roles);
does StringBuilder function properly with maps?

2017-03-14 23:08 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +        // TODO identity.getrole()
Please remove the changes to this file in this commit

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/Session.java
> +        return new FullConnectorSession(queryId.toString(), identity.toConnectorIdentity(), timeZoneKey, locale, startTime);
how does this mean anything?

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/connector/system/SystemConnectorSessionUtil.java
> +                .setIdentity(session.getIdentity().toIdentity())
can you rename the variable to connectorSession?

2017-03-14 23:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/testing/TestingConnectorSession.java
> -    public Identity getIdentity()
how disruptive would it be to rename this to getConnectorIdentity?

2017-03-14 23:08 UTC, cawallin commented on presto-spi/src/main/java/com/facebook/presto/spi/ConnectorSession.java
> -    Identity getIdentity();
in a follow-on commit can you change this to getConnectorIdentity?

2017-03-14 23:08 UTC, cawallin commented on presto-spi/src/main/java/com/facebook/presto/spi/security/ConnectorIdentity.java
> +    public Identity toIdentity()
This method seems potentially dangerous because it's lossy

2017-03-14 23:08 UTC, cawallin commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestingPrestoClient.java
> +                session.getIdentity().getRoles(),
I don't think that ClientSession changed in this commit?

2017-03-14 23:09 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/Session.java
> +        return new FullConnectorSession(queryId.toString(), identity.toConnectorIdentity(), timeZoneKey, locale, startTime);
I see, it's an identity that doesn't have any roles. Is this safe?

2017-03-15 12:58 UTC, amrutagokhale commented
@arhimondr In view of catalog access control, I think we should keep the access control checks for `SHOW GRANTS`. Otherwise, the command would not throw an exception even when the user doesn't have access to a catalog.

2017-03-15 17:27 UTC, cawallin requested changes

2017-03-15 17:27 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +                privilegeInfo.getGrantor().getName(),
? It looks like you're switching grantee and grantor here, how does that work? Don't you need both?

2017-03-15 17:27 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/PermissionMetadata.java
> +        return new HivePrivilegeInfo(permission, grantOption, new PrestoPrincipal(USER, "admin"));
This isn't necessarily accurate though, right? And it wouldn't even work in one given session, you wouldn't see the actual grantor

2017-03-15 17:27 UTC, cawallin commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java
> +        PrestoPrincipal grantor = new PrestoPrincipal(USER, tableOwner);
Please remove the commit "Add grantor to HivePrivilegeInfo", I don't think it's necessary and we can't fill it in accurately.

2017-03-15 20:03 UTC, amrutagokhale requested changes

2017-03-15 20:03 UTC, amrutagokhale commented on presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowQueriesRewrite.java
> +                    selectList(new AllColumns()),
Is there a need to remove the aliases? The output produced by the original code is more readable, in my opinion.

2017-03-15 20:08 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/sql/rewrite/ShowQueriesRewrite.java
> +                    selectList(new AllColumns()),
From what I just saw with SHOW ROLES, I agree with Amruta here

2017-03-16 21:17 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
>      {
Yes. Admin basically can do everything no matter what.

2017-03-16 21:18 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
> +            boolean grantOptionRequired)
HivePrivilegeInfo now contains `grantor` field, which cannot be populated with any value that make sense in this place.

2017-03-16 21:19 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/security/SqlStandardAccessControl.java
> +            boolean grantOptionRequired)
@cawallin I don't like such methods explosion. Further it is harder to track the data flow, and what method is being used where.

2017-03-16 21:19 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/HivePrivilegeInfo.java
> +                throw new IllegalArgumentException("Unexpected privilege: " + privilege);
No, this is just a sanity check. It should never happen.

2017-03-16 21:35 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/server/HttpRequestSessionFactory.java
> +        identity = new Identity(user, Optional.ofNullable(servletRequest.getUserPrincipal()), parseRoleHeaders(servletRequest));
It is completely internal

2017-03-16 21:35 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/Session.java
> +        return new FullConnectorSession(queryId.toString(), identity.toConnectorIdentity(), timeZoneKey, locale, startTime);
As long as creating session for some abstract connector with no id is safe.

2017-03-16 21:36 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/Session.java
> +                identity.getRoles(),
Yeah. Session representation is just a way we serialize session. Identity is not serializable. So, we pass identity field by field.

2017-03-16 21:36 UTC, arhimondr commented on presto-spi/src/main/java/com/facebook/presto/spi/security/Identity.java
> +        sb.append(", roles=").append(roles);
Yes, it does `.toString()` implicitly

2017-03-16 21:38 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +        // TODO identity.getrole()
I can not. Because at this point Identity no longer has role within. It has a map of roles instead.

2017-03-16 21:40 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/connector/system/SystemConnectorSessionUtil.java
> +                .setIdentity(session.getIdentity().toIdentity())
extracted `session.getIdentity()` to `connectorIdentity` variable

2017-03-16 21:42 UTC, arhimondr commented on presto-main/src/main/java/com/facebook/presto/testing/TestingConnectorSession.java
> -    public Identity getIdentity()
I just wanted to keep the naming consistent with other method from ConnectorSession. There is `getProperty` method, but not `getConnectorProperty`. If you insist - i can change it. But i think it is kind of tautology, `ConnectorSession#getConnectorIdentity`.

2017-03-16 21:42 UTC, arhimondr commented on presto-spi/src/main/java/com/facebook/presto/spi/ConnectorSession.java
> -    Identity getIdentity();
ditto

2017-03-16 21:44 UTC, arhimondr commented on presto-spi/src/main/java/com/facebook/presto/spi/security/ConnectorIdentity.java
> +    public Identity toIdentity()
I agree. This method is used in single place only. Gonna do the same but inline in that place.

2017-03-16 21:47 UTC, arhimondr commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestingPrestoClient.java
> +                session.getIdentity().getRoles(),
It is not. But the place where we take roles did. So, now we retrieve them from identity, instead of directly from Session.

2017-03-16 21:57 UTC, arhimondr commented
@amrutagokhale I removed the commit that removes access control

2017-03-16 21:57 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +                privilegeInfo.getGrantor().getName(),
I was wrong before. Here you should pass grantor, but not grantee.

2017-03-16 21:58 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/metastore/file/PermissionMetadata.java
> +        return new HivePrivilegeInfo(permission, grantOption, new PrestoPrincipal(USER, "admin"));
This class is used in FileHiveMetastore only. And grantor is not supported there. This PR is already huge. Let's implement grantor support for FileHiveMetastore as a separate PR.

2017-03-16 21:59 UTC, arhimondr commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java
> +        PrestoPrincipal grantor = new PrestoPrincipal(USER, tableOwner);
It is accurate here. If you are creating a table - you are a grantor for privileges for yourself. That's what hive is doing.

2017-03-17 18:23 UTC, cawallin commented on presto-main/src/main/java/com/facebook/presto/testing/TestingConnectorSession.java
> -    public Identity getIdentity()
Fair enough, it was just confusing with the rename.

2017-03-17 18:30 UTC, cawallin approved these changes
GJ!

2017-03-17 18:42 UTC, amrutagokhale commented
@arhimondr Now that I think about it, we need access control for "show grants" only in `SystemAccessControl` and not necessarily in `ConnectorAccessControl`. But I guess we can take care of this later, given that it involves editing the commits etc.

2017-03-17 18:42 UTC, amrutagokhale approved these changes

2017-03-17 18:44 UTC, cawallin commented
@amrutagokhale @arhimondr yeah, this all is a temporary measure anyway. I made a ticket to handle this properly, we'll tackle it as soon as we can.

2017-03-17 20:07 UTC, merged