Mapr support maprclient
Teradata/presto pull request #528
Opened 2017-03-24 19:53 UTC by sanjay990

2017-03-24 20:10 UTC, sanjay990 commented
I'll remove the 2nd commit, that's just for my local testing.

2017-03-25 00:47 UTC, akshatnair commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${PRESTO_MASTER_CONTAINER} /opt/mapr/server/configure.sh -N ${HADOOP_HOST_NAME} -c -C ${HADOOP_HOST_NAME}:7222 -HS ${HADOOP_HOST_NAME}
Is this port number 7222 configurable in the MapR container? this should be parameterized or atleast a constant.

2017-03-25 00:47 UTC, akshatnair commented on presto-product-tests/conf/docker/common/standard.yml
> +    # Will replace the image once we have that on docker-hub
Replace what? I am not following this comment, are you talking about the commented image line above this?

2017-03-25 16:54 UTC, sanjay990 commented on presto-product-tests/conf/docker/common/standard.yml
> +    # Will replace the image once we have that on docker-hub
yes, ``image: 'teradatalabs/centos6-java8-oracle-mapr:${DOCKER_IMAGES_VERSION}'``

2017-03-27 14:24 UTC, sanjay990 commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${PRESTO_MASTER_CONTAINER} /opt/mapr/server/configure.sh -N ${HADOOP_HOST_NAME} -c -C ${HADOOP_HOST_NAME}:7222 -HS ${HADOOP_HOST_NAME}
https://github.com/Teradata/presto/pull/528/commits/4a3e015040984ee8bf2373d9481c3ef34d9ac78e

2017-03-27 17:46 UTC, akshatnair commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} chown -R mapr /opt/mapr/httpfs
make /opt/mapr as an env variable for MAPR_HOME  or something and use it everywhere else too.

2017-03-27 17:47 UTC, akshatnair commented
LGTM mod one comment.

2017-03-28 15:43 UTC, ArturGajowy requested changes
please avoid commented out code

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +function presto_master_container(){
formatting

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} maprcli node services -name httpfs -action start -nodes ${HADOOP_HOST_NAME}
why is that done from this script? why doesn't the image do this on startup (in, say, bootstrap.sh?)

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} chown -R mapr ${MAPR_HOME}/httpfs
ditto, this should be done during image startup, or - ideally - during image build

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  HADOOP_MASTER_CONTAINER=$(hadoop_master_container)
this variable is unused

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +sleep 150
write a `check_mapr` funciton  or make check_hadoop check for mapr srevice if running against a mapr container.

2017-03-28 15:43 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/standard.yml
> +    # Will replace the image once we have that on docker-hub
parameterize the image, set the default in compose-commons.sh

2017-03-30 12:08 UTC, ArturGajowy requested changes
Updated according to new context from our slack convo

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} maprcli node services -name httpfs -action start -nodes ${HADOOP_HOST_NAME}
the `hostname` command could be used to get the value of `${HADOOP_HOST_NAME}` inside the container

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} maprcli node services -name httpfs -action start -nodes ${HADOOP_HOST_NAME}
```
Arturs-MBP:presto arturgajowy$ presto-product-tests/conf/docker/singlenode/compose.sh run hadoop-master hostname
hadoop-master
```

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  HADOOP_MASTER_CONTAINER=$(hadoop_master_container)
after getting more context from our slack conversation, I see that the `/server/configure.sh` should be run from a specialized `mapr-presto-launcher-wrapper.sh`. The variables used in this function should be defined in that script. Please don't bother with parametrizing the 'HADOOP_HOST_NAME', it's hardwired everywhere anyway. It's ok to just define the variable in that launcher script.

The specialized wrapper should be used by having a `docker/common/mapr.yml` compose file, added to the `mapr` profile. The `image:` override should take place there as well.

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/conf/docker/common/standard.yml
> +    # Will replace the image once we have that on docker-hub
nvm the 'parameterize the image comment'. This file should not be changed at all for the mapr integration. Instead, there should be a separate `mapr.yml` and a new profile, called `mapr` whose `compose.sh` would include the `mapr.yml` similarly to how all other `compose.sh` work. The image should be overridden in mapr.yml.

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +function presto_master_container(){
This function will be unused after addressing the comments and should be then deleted

2017-03-30 12:08 UTC, ArturGajowy commented on presto-product-tests/bin/run_on_docker.sh
> +  docker exec ${HADOOP_MASTER_CONTAINER} maprcli node services -name httpfs -action start -nodes ${HADOOP_HOST_NAME}
please do this in the image's `bootstrap.sh` (modify the docker image accordignly)

2017-04-03 17:33 UTC, ArturGajowy approved these changes
Looks way simpler and cleaner now :)

2017-04-03 17:33 UTC, ArturGajowy commented on presto-product-tests/conf/docker/singlenode-mapr/compose.sh
> +-f ${BASH_SOURCE%/*}/../common/cassandra.yml \
https://github.com/prestodb/presto/pull/7684 is in master already, but I understand this PR's base does not contain it? I'd prefer we got rid of that before having this in sprint branch

2017-04-03 17:35 UTC, sanjay990 commented on presto-product-tests/conf/docker/singlenode-mapr/compose.sh
> +-f ${BASH_SOURCE%/*}/../common/cassandra.yml \
@ArturGajowy : Yes, will remove this before merging with sprint branch. :)

2017-04-05 02:52 UTC, petroav commented on presto-product-tests/conf/docker/singlenode-mapr/compose.sh
> +-f ${BASH_SOURCE%/*}/../common/cassandra.yml \
This isn't going on the sprint branch. It'll stay on the `mapr-support` branch until we figure out what's going to happen.

2017-04-06 17:43 UTC, closed without merging