Top level unit tests for CostCalculator (v2)
Teradata/presto pull request #530
Opened 2017-03-27 07:12 UTC by kokosing

Supersedes https://github.com/Teradata/presto/pull/525

2017-03-27 11:20 UTC, losipiuk approved these changes

2017-03-27 11:20 UTC, losipiuk commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +        private final List<MetricComparison> metricComparison;
`metricComparisons`

2017-03-27 11:20 UTC, losipiuk commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDisplayTpchDistributedStats.java
> +        IntStream.rangeClosed(1, NUMBER_OF_TPCH_QUERIES)
static import

2017-03-27 11:20 UTC, losipiuk commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDisplayTpchDistributedStats.java
> +            return Resources.toString(getClass().getResource(queryClassPath), Charset.defaultCharset());
UTF-8 would probably be more portable.

2017-03-27 11:20 UTC, losipiuk commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDisplayTpchDistributedStats.java
> +            throw Throwables.propagate(e);
deprecated

2017-03-27 11:56 UTC, ArturGajowy requested changes
looks good, several minors spotted

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +            System.out.println(format("Summary for metric [%s] contains [%s] metrics", metricName, resultSummaries.size()));
contains [%s] results

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +            System.out.println(format("Summary for metric [%s] contains [%s] metrics", metricName, resultSummaries.size()));
`resultSummaries.size()` is always `4` - the number of `Result` enum values. What you're after is sth like `resultSummaries.values().stream().sum(List::size)`

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +
remove blank line

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDisplayTpchDistributedStats.java
> +        IntStream.rangeClosed(1, NUMBER_OF_TPCH_QUERIES)
nit: static import

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +                .outputHas(Metric.OUTPUT_ROW_COUNT, relativeError(Range.closed(-.55, -.45)));
add static import for Metric.*

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +                .outputHas(Metric.OUTPUT_ROW_COUNT, relativeError(Range.closed(.95, 1.05)));
I'd abstract from the output node and talk about the whole query instead. So please rename:
`outputHas` to `hasEstimateFor`. So the test looks like:
```java
     statisticsAssertion.check("SELECT * FROM  part, partsupp WHERE p_partkey = ps_partkey")
                .hasEstimateFor(OUTPUT_ROW_COUNT, relativeError(Range.closed(.95, 1.05)));
```

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +                .outputHasNoEstimate(Metric.OUTPUT_ROW_COUNT);
ditto: drop the `output` part from the method name. `hasNoEstimateFor`?

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +            // TODO: remove passing strategy here
remove the TODO here and below

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +        private Result testMetrics(Predicate<PlanNode> planNodeFilter, Metric metric, Predicate<MetricComparison> assertCondition)
please remove the planNodeFilter and always use the output node for comparison. There's no other use case until we have stable node IDs, and asserting about all the plan nodes is brittle

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +                    .filter(metricComparison -> planNodeFilter.test(metricComparison.getPlanNode()))
this method should raise an assertion error if there's not a result in either of the two lines above. In other words, metric comparisons should contain an element for all metrics, for all nodes.

Alternatively: maybe we should introduce a `MetricComparisons` class to guard this property?

I think this adds weight to the previous comment (remove `planNodeFilter`) as applying it only leaves us with the assumption, that there's a MetricComparison for all metrics, for the root node only)

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/main/java/com/facebook/presto/tests/statistics/StatisticsAssertion.java
> +            return match(alwaysTrue(), Metric.OUTPUT_ROW_COUNT, defaultTolerance());
let's not make OUTPUT_ROW_COUNT special in the API. Please replace the only usage with:

`statisticsAssertion.check(query).hasEstimateFor(OUTPUT_ROW_COUNT, noError())`

2017-03-27 11:56 UTC, ArturGajowy commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchDistributedStats.java
> +    void testSetOperationsj()
typo

2017-03-27 11:59 UTC, ArturGajowy commented
👍  for starting it against the epic branch :)

2017-03-28 12:10 UTC, kokosing commented
Superseded by #533

2017-03-28 12:10 UTC, closed without merging