epic/statistics-7 tests fixups
Teradata/presto pull request #576
Opened 2017-06-16 12:12 UTC by fiedukow

2017-06-16 13:14 UTC, losipiuk requested changes

2017-06-16 13:14 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +            if (leftStats == null || rightStats == null ||
If you use `input.getSymbolStatistics(left)` instead `input.getSymbolStatistics().get(left)` you will not need to check for null.

2017-06-16 13:14 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +            if (symbolStats == null) {
same comment here.

2017-06-16 15:41 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/SymbolStatsEstimate.java
> +        return distinctValuesCount != 0 || isNaN(lowValue) || isNaN(highValue);
distinctValuesCount != 0 || (!isNaN(lowValue) && !isNaN(highValue));

2017-06-19 15:20 UTC, fiedukow commented
merged into epic/statistics-9

2017-06-19 15:20 UTC, closed without merging