Add statistic estimation for simple AggregationNode
Teradata/presto pull request #590
Opened 2017-06-22 12:22 UTC by kokosing

Add statistic estimation for simple AggregationNode

2017-06-22 13:09 UTC, losipiuk commented
Fix compilation errors

2017-06-23 08:37 UTC, sopel39 approved these changes

2017-06-23 09:45 UTC, losipiuk requested changes

2017-06-23 09:45 UTC, losipiuk commented on presto-main/src/test/java/com/facebook/presto/cost/TestOutputNodeStats.java
> -            throws Exception
Please add such commits using `--fixup=<commit_to_be_fixed>`
It spares me an effort of finding the commit I should squash it to.

2017-06-23 09:45 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/AggregationStatsRule.java
> +        if (!sourceStats.getSymbolsWithKnownStatistics().containsAll(groupBySymbols)) {
What about the case that statistics are known but some parts of those are not (e.g. distinctValuesCount, nullsFraction).
I would rather drop this if. And make sure the loops below behave correctly.
Can you add test cases for such cases?

2017-06-23 09:45 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/AggregationStatsRule.java
> +        if (!sourceStats.getSymbolsWithKnownStatistics().containsAll(groupBySymbols)) {
Probably it can be handled by checking at the bottom of method that `rowsCount` is `NaN` and return UNKNOWN_STATS in such case.

2017-06-23 09:45 UTC, losipiuk commented on presto-tests/src/test/java/com/facebook/presto/tests/TestTpchLocalStats.java
> +        statisticsAssertion.check("SELECT n_name, count() AS count FROM nation GROUP BY n_name",
Test without GROUP BY.
Also use query where with some non-uniqe values within grouping set.
E.g. `SELECT n_name, count() AS count FROM nation,region GROUP BY n_name;`

2017-06-23 09:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/cost/AggregationStatsRule.java
> +                }
You should explicitly handle `nullsFraction` that is `NaN`.

2017-06-23 09:48 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/cost/AggregationStatsRule.java
> +            int nullRow = symbolStatistics.getNullsFraction() > 0 ? 1 : 0;
ditto. `NaN` nulls fraction would make `nullRow=0`

2017-06-27 08:11 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/cost/AggregationStatsRule.java
> +        if (!sourceStats.getSymbolsWithKnownStatistics().containsAll(groupBySymbols)) {
Why should I return UNKNOWN_STATS while I was able to calculate something? Is it not better to return this what I was able to calculate than nothing?

2017-06-27 08:54 UTC, kokosing commented
@sopel39 @losipiuk Comments addressed, can you please take another look?

2017-06-27 09:28 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/SymbolStatsEstimate.java
> +        return buildFrom(this).setHighValue(mappingFunction.apply(distinctValuesCount)).build();
`setHighValue` should be `setDistinctValuesCount`

2017-06-27 16:29 UTC, losipiuk commented
Looks good modulo one type I pointed.

2017-06-28 10:01 UTC, merged