Introduce statistic estimation normalizers
Teradata/presto pull request #593
Opened 2017-06-27 11:18 UTC by kokosing

2017-06-27 13:12 UTC, fiedukow requested changes

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToOutputRowsCount.java
> +            normalized.addSymbolStatistics(symbol, estimate.getSymbolStatistics(symbol)
You can avoid explicit builder creation here by using something like:
```
estimate.mapSymbolColumnStatistics(
  symbol, symbolStats ->
    symbolStats.mapDistinctValuesCount(
      distinctValuesCount -> min(distinctValuesCount, outputRowCount)));
```

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/server/ServerMainModule.java
> +
Seems like unwanted change

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/test/java/com/facebook/presto/cost/TestCapDistinctValuesCountToOutputRowsCount.java
> +        PlanNodeStatsEstimate estimate = PlanNodeStatsEstimate.builder()
I would at least add second symbol that will not be affected by Normalizer to cover basic scenario.

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/test/java/com/facebook/presto/cost/TestCapDistinctValuesCountToOutputRowsCount.java
> +        PlanNodeStatsEstimate normalized = normalizer.normalize(null, estimate, null);
I don't like nulls here - it is implementation dependent. In fact, I would say we could `checkArgument`s for nulls in `normalize` method.

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +        return type.equals(IntegerType.INTEGER) ||
This definition should also contain decimal with scale of zero.
Also, I would reuse the `ScalarStatsCalculator::isIntegralType` code.

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +                    .mapDistinctValuesCount(distinctValuesCount -> Math.min(distinctValuesCount, domainLength)));
Isn't it wrong for the `isNaN(domainLenght)` case?

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +            normalized.addSymbolStatistics(symbol, estimate.getSymbolStatistics(symbol)
Same comment about possible avoidance of explicit builder.

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +        return symbolStatistics.getHighValue() - symbolStatistics.getLowValue() + 1;
I think round down to whole value would be justifiable.
Also I think you can just `ceil(symbolStatistics.getHighValue() - symbolStatistics.getLowValue())` (without adding 1.

2017-06-27 13:12 UTC, fiedukow commented on presto-main/src/test/java/com/facebook/presto/cost/TestCapDistinctValuesCountToTypeDomainRangeLength.java
> +    public void test()
Add case for DECIMAL (both Integral and not integral).
Add case for non integral type (eg. DOUBLE).
Add case for integral type that will have stats unaffected by normalizer (range > ndv)

2017-06-28 11:18 UTC, losipiuk requested changes

2017-06-28 11:18 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToOutputRowsCount.java
> +            normalized.addSymbolStatistics(symbol, estimate.getSymbolStatistics(symbol)
+1

2017-06-28 11:18 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToOutputRowsCount.java
> +    public PlanNodeStatsEstimate normalize(PlanNode node, PlanNodeStatsEstimate estimate, Map<Symbol, Type> types)
add `rnn` for params.

2017-06-28 11:18 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +        return type.equals(IntegerType.INTEGER) ||
Actually for decimal with scale != 0 we also can compute the number of values within range. The important thing here is not if type is integral but if it is not dense.

2017-06-28 11:18 UTC, losipiuk commented on presto-main/src/test/java/com/facebook/presto/cost/TestEnsureAllOutputSymbolsHaveStats.java
> +public class TestEnsureAllOutputSymbolsHaveStats
It would also be nice to prune stats for unnecessary symbols here.
Then it could be named `EnsureStatsMatchOutputs`

2017-06-28 12:48 UTC, kokosing reviewed
@losipiuk @fiedukow Comments addressed. Thanks for great comments! :)

2017-06-28 12:48 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/cost/CapDistinctValuesCountToTypeDomainRangeLength.java
> +        return symbolStatistics.getHighValue() - symbolStatistics.getLowValue() + 1;
I will use floor instead :)

2017-06-28 12:48 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/cost/TestEnsureAllOutputSymbolsHaveStats.java
> +public class TestEnsureAllOutputSymbolsHaveStats
I do prune, see that b is pruned.
I will rename.

2017-06-28 13:06 UTC, fiedukow approved these changes

2017-06-29 10:38 UTC, merged