Use pattern matching in ComposableStatsCalculator
Teradata/presto pull request #594
Opened 2017-06-28 11:06 UTC by kokosing

Use pattern matching in ComposableStatsCalculator

2017-06-28 11:19 UTC, kokosing commented
The first commit comes from https://github.com/prestodb/presto/pull/8376, in case of comments to that commit, please comment in oryginal PR.

2017-06-29 06:22 UTC, losipiuk requested changes

2017-06-29 06:22 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/matching/MatchablesStore.java
> +    private static Iterator<Class> ancestors(Class clazz)
I know it was here before.
But this method does not look good. It does not handle interfaces correctly.

More correct, but possibly less performant approach would be to implement `getCandidates` as iteration over keys of `matchablesByClass` 
and for each check if `key.isInstance(object)`

2017-06-29 06:22 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/matching/MatchablesStore.java
> +public class MatchablesStore<T extends Matchable>
I do not think we should use `<T extends Matchable>` here. It unnecessary adds class hierarchy dependency for users of `MatchableStore`. 

It should be 
```
public class MatchablesStore<T>
```

And in `Builder` we could have two methods
```
register(T matchable, Pattern pattern) {
   ....
} 
register(T matchable) {
   checkArgument(matchable instanceOf Matchable);
   register(matchable, ((Matchable)matchable).getPattern())
}

2017-06-29 06:22 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/matching/MatchablesStore.java
> +    {
Also I do no like the name `MatchablesStore`. Storing matchables is not main responsibility. Matching is.
I would call it `MatchingEngine`

2017-06-29 06:22 UTC, losipiuk commented on presto-main/src/main/java/com/facebook/presto/util/MoreMath.java
> -
unrelated

2017-06-29 06:22 UTC, losipiuk commented
Travis failed (probably due to errors in base branch)

2017-06-29 12:13 UTC, merged