Document cost-based join reordering
Teradata/presto pull request #596
Opened 2017-06-28 20:54 UTC by rschlussel

2017-06-28 21:44 UTC, akshatnair approved these changes
LGTM mod a small change

2017-06-28 21:44 UTC, akshatnair commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +are only available in the hive connector). It will then choose the join order with the lowest
s/hive/Hive

2017-06-29 14:23 UTC, kbajda requested changes
Please clarify what about the replicated joins? It used to be a separate property independent of "cross join elimination".  Is "cost-based" doing that automatically now? What if someone selects "eliminate-cross-joins" instead? any chance for them to get replicated joins via setting another property?

2017-06-29 14:23 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +When the join reordering strategy is set to ``COST_BASED``, Presto will use statistics
Let's link to a section of docs describing Stats in Presto. How to gather them, display etc.

2017-06-29 14:23 UTC, KBP-TDC commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +orders for many tables is computationally intensive, so joins are reordered in groups of ten at a time.
Could you explain what happens if a query has more than 10 joins, say 12? Would 10 first joins be reordered between them and then the remaining 2 will be reordered separately? and the clusters of 10 and 2 will be merged without considering any cost between the two groups?

2017-06-29 14:28 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +orders for many tables is computationally intensive, so joins are reordered in groups of ten at a time.
yes.

2017-06-29 14:29 UTC, rschlussel commented
Repartitioned vs. replicated vs. automatic is still a separate property that is enforced regardless of the join reordering strategy.  It has its own docs that haven't changed from last time.

2017-06-29 14:37 UTC, KBP-TDC commented
> is still a separate property
If so, please make sure we mention that and link to that doc section somehow and explain that for full cost-based benefit, one needs to enable both things.

2017-06-29 20:08 UTC, rschlussel commented on presto-docs/src/main/sphinx/optimizer/reorder-joins.rst
> +When the join reordering strategy is set to ``COST_BASED``, Presto will use statistics
I'll have to do that later when I rebase this on top of the stats and join enumeration branches.

2017-07-11 21:10 UTC, rschlussel commented
merged to  the sprint branch.

2017-07-11 21:10 UTC, closed without merging