Handle symbol = symbol explicitly in stats
Teradata/presto pull request #692
Opened 2017-08-18 12:46 UTC by sopel39

2017-08-18 13:39 UTC, losipiuk requested changes

2017-08-18 13:39 UTC, losipiuk commented on presto-main/src/test/java/com/facebook/presto/cost/TestFilterStatsCalculator.java
> +    public void testSymbolEqualsSymbolFilter()
rename to `testSymbolEqualsSameSymbolFilter()`

2017-08-21 10:30 UTC, findepi requested changes

2017-08-21 10:30 UTC, findepi commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +            if (left instanceof SymbolReference && right instanceof SymbolReference && left.equals(right)) {
When such a condition can be created?

2017-08-21 10:30 UTC, findepi commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +                // any non-null value pass filter condition
"passes"

anyway, you'd better delegate to handling of `IS NOT NULL`

2017-08-21 10:30 UTC, findepi commented on presto-main/src/test/java/com/facebook/presto/cost/TestFilterStatsCalculator.java
> +        Expression leftExpressionSingleValue = new ComparisonExpression(EQUAL, new SymbolReference("x"), new DoubleLiteral("0.0"));
unrelated change (here & below). Each such a change should be a fixup to the right commit

2017-08-21 10:30 UTC, findepi commented on presto-main/src/test/java/com/facebook/presto/cost/TestFilterStatsCalculator.java
> +        // Impossible, with symbol-to-expression comparisons
should be a fixup

2017-08-21 10:30 UTC, findepi commented on presto-main/src/test/java/com/facebook/presto/cost/TestFilterStatsCalculator.java
> +        Expression symbolEqualsSymbol = new ComparisonExpression(EQUAL, new SymbolReference("x"), new SymbolReference("x"));
I think we shouldn't have unit test for that, as the (more) correct solution would be to fix the party responsible for introducing/retaining such (almost) useless comparison. We _do_ need an integration test, however, e.g. in `TestTpchLocalStats`

2017-08-21 12:32 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +            if (left instanceof SymbolReference && right instanceof SymbolReference && left.equals(right)) {
you know by now...

2017-08-21 12:43 UTC, findepi commented on presto-main/src/main/java/com/facebook/presto/cost/FilterStatsCalculator.java
> +            if (left instanceof SymbolReference && right instanceof SymbolReference && left.equals(right)) {
I still don't :) I tried, but i failed.

2017-08-21 12:57 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/cost/TestFilterStatsCalculator.java
> +        Expression symbolEqualsSymbol = new ComparisonExpression(EQUAL, new SymbolReference("x"), new SymbolReference("x"));
I wouldn't call `a=a` is a bug. It is a perfectly legal expression. If we can test it on unit level (even as a special case), then why not?

2017-08-21 13:20 UTC, sopel39 commented
applied comments

2017-08-21 13:54 UTC, losipiuk approved these changes

2017-08-21 13:54 UTC, closed without merging